<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>VDS_Editor_2025_CAD</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Vault\**" />
    <EmbeddedResource Remove="Vault\**" />
    <None Remove="Vault\**" />
    <Page Remove="Vault\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\cs-CZ\PropertyTranslations.xml" Link="cs-CZ\PropertyTranslations.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\cs-CZ\UIStrings.xml" Link="cs-CZ\UIStrings.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\de-DE\PropertyTranslations.xml" Link="de-DE\PropertyTranslations.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\de-DE\UIStrings.xml" Link="de-DE\UIStrings.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\en-US\PropertyTranslations.xml" Link="en-US\PropertyTranslations.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\en-US\UIStrings.xml" Link="en-US\UIStrings.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\es-ES\PropertyTranslations.xml" Link="es-ES\PropertyTranslations.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\es-ES\UIStrings.xml" Link="es-ES\UIStrings.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\fr-FR\PropertyTranslations.xml" Link="fr-FR\PropertyTranslations.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\fr-FR\UIStrings.xml" Link="fr-FR\UIStrings.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\hu-HU\PropertyTranslations.xml" Link="hu-HU\PropertyTranslations.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\hu-HU\UIStrings.xml" Link="hu-HU\UIStrings.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\it-IT\PropertyTranslations.xml" Link="it-IT\PropertyTranslations.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\it-IT\UIStrings.xml" Link="it-IT\UIStrings.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\ja-JP\PropertyTranslations.xml" Link="ja-JP\PropertyTranslations.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\ja-JP\UIStrings.xml" Link="ja-JP\UIStrings.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\ko-KR\PropertyTranslations.xml" Link="ko-KR\PropertyTranslations.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\ko-KR\UIStrings.xml" Link="ko-KR\UIStrings.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\pl-PL\PropertyTranslations.xml" Link="pl-PL\PropertyTranslations.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\pl-PL\UIStrings.xml" Link="pl-PL\UIStrings.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\pt-BR\PropertyTranslations.xml" Link="pt-BR\PropertyTranslations.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\pt-BR\UIStrings.xml" Link="pt-BR\UIStrings.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\ru-RU\PropertyTranslations.xml" Link="ru-RU\PropertyTranslations.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\ru-RU\UIStrings.xml" Link="ru-RU\UIStrings.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\zh-CN\PropertyTranslations.xml" Link="zh-CN\PropertyTranslations.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\zh-CN\UIStrings.xml" Link="zh-CN\UIStrings.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\zh-TW\PropertyTranslations.xml" Link="zh-TW\PropertyTranslations.xml" />
    <Content Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\zh-TW\UIStrings.xml" Link="zh-TW\UIStrings.xml" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CAD.Custom\Configuration\" />
    <Folder Include="CAD\addins\" />
    <Folder Include="CAD\Configuration\" />
    <Folder Include="cs-CZ\" />
    <Folder Include="de-DE\" />
    <Folder Include="en-US\" />
    <Folder Include="es-ES\" />
    <Folder Include="fr-FR\" />
    <Folder Include="hu-HU\" />
    <Folder Include="it-IT\" />
    <Folder Include="ja-JP\" />
    <Folder Include="ko-KR\" />
    <Folder Include="pl-PL\" />
    <Folder Include="pt-BR\" />
    <Folder Include="ru-RU\" />
    <Folder Include="SDK-Refs\" />
    <Folder Include="zh-CN\" />
    <Folder Include="zh-TW\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\CAD\addins\breadCrumb.ps1" Link="CAD\addins\breadCrumb.ps1" />
    <None Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\CAD\addins\Default.ps1" Link="CAD\addins\Default.ps1" />
    <None Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\CAD\addins\FileNameValidation.ps1" Link="CAD\addins\FileNameValidation.ps1" />
    <None Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\CAD\Configuration\AutoCAD.cfg" Link="CAD\Configuration\AutoCAD.cfg" />
    <None Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\CAD\Configuration\Inventor.cfg" Link="CAD\Configuration\Inventor.cfg" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\CAD\Configuration\AutoCAD.xaml" Link="CAD\Configuration\AutoCAD.xaml" />
    <Page Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\CAD\Configuration\CableAndHarness.xaml" Link="CAD\Configuration\CableAndHarness.xaml" />
    <Page Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\CAD\Configuration\DesignAccelerator.xaml" Link="CAD\Configuration\DesignAccelerator.xaml" />
    <Page Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\CAD\Configuration\FrameGenerator.xaml" Link="CAD\Configuration\FrameGenerator.xaml" />
    <Page Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\CAD\Configuration\Inventor.xaml" Link="CAD\Configuration\Inventor.xaml" />
    <Page Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\CAD\Configuration\SaveCopyAs.xaml" Link="CAD\Configuration\SaveCopyAs.xaml" />
    <Page Include="..\..\..\..\..\..\ProgramData\Autodesk\Vault 2025\Extensions\DataStandard\CAD\Configuration\TubeAndPipe.xaml" Link="CAD\Configuration\TubeAndPipe.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Autodesk.Connectivity.WebServices">
      <HintPath>SDK-Refs\Autodesk.Connectivity.WebServices.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.DataManagement.Client.Framework.Forms">
      <HintPath>SDK-Refs\Autodesk.DataManagement.Client.Framework.Forms.dll</HintPath>
    </Reference>
    <Reference Include="dataStandard.UI">
      <HintPath>SDK-Refs\dataStandard.UI.dll</HintPath>
    </Reference>
    <Reference Include="log4net">
      <HintPath>SDK-Refs\log4net.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
